namespace Spice86.Tests.Dos;

using FluentAssertions;

using System.IO;

using Xunit;

using static BatchTestHelpers;

/// <summary>
/// Integration tests for the AUTOEXEC.BAT bootstrap mechanism inspired by dosbox-staging.
/// Every host-requested DOS program (COM, EXE, BAT) is routed through a synthetic
/// Z:\AUTOEXEC.BAT generated by <see cref="Spice86.Core.Emulator.OperatingSystem.DosBatchExecutionEngine.ConfigureHostStartupProgram"/>.
/// </summary>
public class BootstrapAutoexecIntegrationTests {

    [Fact]
    public void Bootstrap_HostRequestedExe_ExecutesThroughAutoexecBat() {
        WithTempDirectory("boot_exe", tempDir => {
            // Arrange: .EXE extension with flat-binary (COM-format) content.
            // The program loader falls back to COM loading when the MZ header is absent,
            // but the bootstrap routing still uses the .EXE path in AUTOEXEC.BAT.
            CreateBinaryFile(tempDir, "GAME.EXE", BuildVideoWriterCom('X', 0));

            // Act
            char actual = RunAndCaptureVideoCell(Path.Join(tempDir, "GAME.EXE"), tempDir);

            // Assert
            actual.Should().Be('X');
        });
    }

    [Fact]
    public void Bootstrap_HostRequestedExeInSubdirectory_ExecutesThroughAutoexecBat() {
        WithTempDirectory("boot_exe_subdir", tempDir => {
            // Arrange: program living in a subdirectory, like C:\GAMES\DUNE\DUNE.EXE
            string subDir = Path.Join(tempDir, "GAMES", "DUNE");
            Directory.CreateDirectory(subDir);
            CreateBinaryFile(subDir, "DUNE.EXE", BuildVideoWriterCom('D', 0));

            // Act
            char actual = RunAndCaptureVideoCell(Path.Join(subDir, "DUNE.EXE"), tempDir);

            // Assert
            actual.Should().Be('D');
        });
    }

    [Fact]
    public void Bootstrap_HostRequestedProgramWithSpacesInPath_IsProperlyQuotedInAutoexecBat() {
        WithTempDirectory("boot spaces", tempDir => {
            // Arrange: directory with a space in its name.
            // BuildCallLine uses EscapeIfNeeded which wraps the DOS path in quotes.
            string spacedDir = Path.Join(tempDir, "MY GAMES");
            Directory.CreateDirectory(spacedDir);
            CreateBinaryFile(spacedDir, "APP.COM", BuildVideoWriterCom('S', 0));

            // Act
            char actual = RunAndCaptureVideoCell(Path.Join(spacedDir, "APP.COM"), tempDir);

            // Assert
            actual.Should().Be('S');
        });
    }

    [Fact]
    public void Bootstrap_HostRequestedBatch_UsesCallToRouteAndReturnsToBatchEngine() {
        WithTempDirectory("boot_bat", tempDir => {
            // Arrange: host-requested file is a BAT that chains into a COM.
            // The bootstrap generates: CALL C:\START.BAT
            // The batch engine then processes START.BAT, which calls WRITER.COM.
            CreateBinaryFile(tempDir, "WRITER.COM", BuildVideoWriterCom('B', 0));
            string batPath = CreateTextFile(tempDir, "START.BAT", "CALL WRITER.COM\r\n");

            // Act
            char actual = RunAndCaptureVideoCell(batPath, tempDir);

            // Assert
            actual.Should().Be('B');
        });
    }

    [Fact]
    public void Bootstrap_ArgumentsPassedFromHost_ArePreservedThroughAutoexecBat() {
        WithTempDirectory("boot_args", tempDir => {
            // Arrange: the host provides ExeArgs that flow into AUTOEXEC.BAT via BuildCallLine.
            // The batch file receives them as %1, %2 etc. A route batch dispatches based on %1.
            CreateBinaryFile(tempDir, "W_YES.COM", BuildVideoWriterCom('Y', 0));
            string batPath = CreateTextFile(tempDir, "ROUTE.BAT",
                "IF \"%1\"==\"RUN\" CALL W_YES.COM\r\n");

            // Act: pass "RUN" as argument to the requested batch
            char actual = RunAndCaptureVideoCell(batPath, tempDir, exeArgs: "RUN");

            // Assert
            actual.Should().Be('Y');
        });
    }

    [Fact]
    public void Bootstrap_ErrorlevelFromProgram_PropagatesThroughAutoexecBatChain() {
        WithTempDirectory("boot_errorlevel", tempDir => {
            // Arrange: host-requested batch chains exit-code + errorlevel check.
            // The autoexec routing preserves the errorlevel across the CALL chain.
            CreateBinaryFile(tempDir, "EXIT3.COM", BuildExitCodeCom(3));
            CreateBinaryFile(tempDir, "W_OK.COM", BuildVideoWriterCom('K', 0));
            string batPath = CreateTextFile(tempDir, "CHECK.BAT",
                "CALL EXIT3.COM\r\nIF ERRORLEVEL 3 CALL W_OK.COM\r\n");

            // Act
            char actual = RunAndCaptureVideoCell(batPath, tempDir);

            // Assert
            actual.Should().Be('K');
        });
    }

}
